title: Koci's blog 
description: writing about  life 
author: Koci 
remote_theme: pages-themes/minimal@v0.2.0
theme: minimal

url: "https://konstantinopoll.github.io/"
baseurl: ""

timezone: Europe/Sofia
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

exclude:
  -README.md
  -LICENSE
 